function [eps] = defineEpochYoung(nantype)

names={'Base','Slow','Fast', 'EarlyA', 'LateA' ,'EarlyP', 'LateP'};

eps=defineEpochs(names,...
                {'TM Base','TM Slow','TM Fast','gradual adaptation','gradual adaptation','TM post', 'TM Post'},...
                [-40 -40 -40 15 -40 15 -40],...
                [0,0,1,1,0,1,0],...
                [1,1,0,0,1,0,1],...
                nantype);